[package]
name = "aoc-helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"

[[bin]]
name = "aoc-new"
path = "src/bin/new.rs"